Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using soprosopro.Models;

namespace soprosopro.Controllers
{
    public class GenresController : Controller
    {
        private readonly soprosoproContext _context;

        public GenresController(soprosoproContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
              return _context.Genre != null ? 
                          View(await _context.Genre.ToListAsync()) :
                          Problem("Entity set 'soprosoproContext.Genre'  is null.");
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GenreId,Type")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GenreId,Type")] Genre genre)
        {
            if (id != genre.GenreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.GenreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Genre == null)
            {
                return Problem("Entity set 'soprosoproContext.Genre'  is null.");
            }
            var genre = await _context.Genre.FindAsync(id);
            if (genre != null)
            {
                _context.Genre.Remove(genre);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
          return (_context.Genre?.Any(e => e.GenreId == id)).GetValueOrDefault();
        }
    }
}

Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using soprosopro.Models;
using soprosopro.ViewModels;


namespace soprosopro.Controllers
{
    public class MoviesController : Controller
    {
        private readonly soprosoproContext _context;

        public MoviesController(soprosoproContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            var index = _context.Movie
            .Include(m => m.Genres).ThenInclude(m => m.Genres)
            .Include(m => m.Actors).ThenInclude(m => m.Actor)
            .Include(m => m.Directors).ThenInclude(m => m.Director)
            .Include(m => m.Producers).ThenInclude(m => m.Producer)
            .AsNoTracking();
            await _context.SaveChangesAsync();
            return View(index);
            return _context.Movie != null ?
                          View(await _context.Movie.ToListAsync()) :
                          Problem("Entity set 'SoproTestContext.Movie'  is null.");

        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Movie == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .Include(m => m.Genres).ThenInclude(m => m.Genres)
                .Include(m => m.Actors).ThenInclude(m => m.Actor)
                .Include(m => m.Directors).ThenInclude(m => m.Director)
                .Include(m => m.Producers).ThenInclude(m => m.Producer)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.MovieId == id);

            await _context.SaveChangesAsync();
            if (movie == null)
            {
                return NotFound();
            }
            await _context.SaveChangesAsync();
            return View(movie);
        }
        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MovieId,Title")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            await _context.SaveChangesAsync();
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Movie == null)
            {
                return NotFound();
            }


            var movie = _context.Movie.Where(m => m.MovieId == id)
               .Include(m => m.Genres)
               .Include(m => m.Actors)
               .Include(m => m.Producers)
               .Include(m => m.Directors)
               .First();

            
            if (movie == null)
            {
                return NotFound();
            }


            var genres = _context.Genre.AsEnumerable();
            genres = genres.OrderBy(s => s.Type);

            var actors = _context.Person.AsEnumerable();
            actors = actors.OrderBy(s => s.Name);

            var directors = _context.Person.AsEnumerable();
            directors = directors.OrderBy(s => s.Name);

            var producers = _context.Person.AsEnumerable();
            producers = producers.OrderBy(s => s.Name);

            await _context.SaveChangesAsync();
            SelectGenres viewmodel = new SelectGenres
            {
                Movie = movie,
                GenreList = new MultiSelectList(genres, "GenreId", "Type"),
                SelectedGenres = movie.Genres.Select(s => s.GenreId),
                ActorList = new MultiSelectList(actors, "PersonId", "Name"),
                SelectedActors = movie.Actors.Select(s => s.ActorId),
                ProducerList = new MultiSelectList(producers, "PersonId", "Name"),
                SelectedProducers = movie.Producers.Select(s => s.ProducerId),
                DirectorList = new MultiSelectList(directors, "PersonId", "Name"),
                SelectedDirectors = movie.Directors.Select(s => s.DirectorId)
            };
            await _context.SaveChangesAsync();
            return View(viewmodel);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SelectGenres viewmodel)
        {
            if (id != viewmodel.Movie.MovieId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viewmodel.Movie);
                    await _context.SaveChangesAsync();

                    IEnumerable<int> listG = viewmodel.SelectedGenres;
                    IEnumerable<int> listActors = viewmodel.SelectedActors;
                    IEnumerable<int> ld = viewmodel.SelectedDirectors;
                    IEnumerable<int> pd = viewmodel.SelectedProducers;
                    //GENRES
                    IQueryable<MovieGenres> toBeRemoved = _context.MovieGenres.Where(s => !listG.Contains(s.GenreId) && s.MovieId == id);
                    _context.MovieGenres.RemoveRange(toBeRemoved);
                    await _context.SaveChangesAsync();

                    IEnumerable<int> existg = _context.MovieGenres.Where(s => listG.Contains(s.GenreId) && s.MovieId == id).Select(s => s.GenreId);
                    IEnumerable<int> newg = listG.Where(s => !existg.Contains(s));
                    await _context.SaveChangesAsync();
                    foreach (int gi in newg)
                         _context.MovieGenres.Add(new MovieGenres { MovieId = id, GenreId = gi });
                    
                    await _context.SaveChangesAsync();
                    //ACTOS

                    IQueryable<MovieActors> BeRemoved = _context.MovieActors.Where(s => !listActors.Contains(s.ActorId) && s.MovieId == id);
                    _context.MovieActors.RemoveRange(BeRemoved);
                    await _context.SaveChangesAsync();

                    IEnumerable<int> existActors = _context.MovieActors.Where(s => listActors.Contains(s.ActorId) && s.MovieId == id).Select(s => s.ActorId);
                    IEnumerable<int> newActors = listActors.Where(s => !existActors.Contains(s));
                    foreach (int actorId in newActors)
                        _context.MovieActors.Add(new MovieActors { ActorId = actorId, MovieId = id });
                    await _context.SaveChangesAsync();

                    //DIRECTORS
                    IQueryable<MovieDirectors> Removed = _context.MovieDirectors.Where(s => !ld.Contains(s.DirectorId) && s.MovieId == id);
                    _context.MovieDirectors.RemoveRange(Removed);
                    await _context.SaveChangesAsync();

                    IEnumerable<int> ed = _context.MovieDirectors.Where(s => ld.Contains(s.DirectorId) && s.MovieId == id).Select(s => s.DirectorId);
                    IEnumerable<int> na = ld.Where(s => !ed.Contains(s));
                    foreach (int di in na)
                        _context.MovieDirectors.Add(new MovieDirectors { DirectorId = di, MovieId = id });
                    await _context.SaveChangesAsync();

                    //PRODUCERS
                    IQueryable<MovieProducers> ved = _context.MovieProducers.Where(s => !pd.Contains(s.ProducerId) && s.MovieId == id);
                    _context.MovieProducers.RemoveRange(ved);
                    await _context.SaveChangesAsync();

                    IEnumerable<int> ep = _context.MovieProducers.Where(s => pd.Contains(s.ProducerId) && s.MovieId == id).Select(s => s.ProducerId);
                    IEnumerable<int> np = pd.Where(s => !ep.Contains(s));
                    foreach (int prd in np)
                        _context.MovieProducers.Add(new MovieProducers { ProducerId = prd, MovieId = id });
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(viewmodel.Movie.MovieId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            await _context.SaveChangesAsync();
            return View(viewmodel);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Movie == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
               .Include(m => m.Genres).ThenInclude(m => m.Genres)
               .Include(m => m.Actors).ThenInclude(m => m.Actor)
               .Include(m => m.Directors).ThenInclude(m => m.Director)
               .Include(m => m.Producers).ThenInclude(m => m.Producer)
               .AsNoTracking()
               .FirstOrDefaultAsync(m => m.MovieId == id);
          
            if (movie == null)
            {
                return NotFound();
            }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <title>@ViewData["Title"] - Sopro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/soprosopro.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">:)</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                                </li>
                            }
                             @if (User.Identity.IsAuthenticated && User.IsInRole("Client"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="MoviesClient">Movies</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Genres" asp-action="Index">Genres</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
                            </li>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="Index">Client</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - soprosopro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>